### ISSUE TITLE
missing 'applyEndPatternLast' and 'while' properties

### ISSUE THREAD

**Issue by msftrncs** [martinring/tmlanguage#1]
The schema is missing 'applyEndPatternLast' and 'while' properties.  These are kind of obscure, though the markdown syntax uses 'while' a bit.  'applyEndPatternLast' needs to be used more, as its important for block constructs that allow the end block to be doubled over within the block. `"quoted""string"`.

**Comment by martinring** [comment]
These do not appear in the official documentation at https://macromates.com/manual/en/language_grammars. I am aware that they exist, but do you have a pointer where they are defined?

**Comment by martinring** [comment]
I added both in 2cc7a1beee23042a0daf3240bd538b3151904687 but would like to add documentation

**Comment by msftrncs** [comment]
Yes, documentation for these is soo sketchy.  It took me a long time to pick up on them.   Myself I haven't found much use in the 'while', but I use 'applyEndPatternLast' quite a bit.

I think these are part of TextMate 2.0.

I am afraid TextMate might never get around to finishing the manual.  I'd really like to read their explanation of '\G'

References:
[Writing a TextMate Grammar: Some Lessons Learned](http://www.apeth.com/nonblog/stories/textmatebundle.html)

[Chapter 14 - Language Grammars - TextMate Manual](https://macromates.com/textmate/manual/language-grammars) - this appears to be a early draft, and only the outline seems to exist, as if its an extension to version 1.x, but this page references the 'begin\while rules'
