### ISSUE TITLE
Add to schemastore.org?

### ISSUE THREAD

**Issue by myitcv** [martinring/tmlanguage#11]
Hi - thanks for this project. It is, as far as I can tell, the only JSON Schema specification of the TextMate grammar out there.

Perhaps to increase visibility you might consider adding the project to https://www.schemastore.org/json/?

It's through that initiative that I found the GitHub actions workflow schemas, OpenAPI and others.

**Comment by martinring** [comment]
it seems like a fork is already on there: https://raw.githubusercontent.com/Septh/tmlanguage/master/tmLanguage.schema.json
