### ISSUE TITLE
VSCode Prescribed use of Patterns flagged as missing Begin Property

### ISSUE THREAD

**Issue by aamarks** [martinring/tmlanguage#4]
Why does this flag `patterns` if they come directly under an item in repository without a begin/end?

An example straight from the documentation gets warnings:
https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide
```
{
  "scopeName": "source.abc",
  "patterns": [{ "include": "#expression" }],
  "repository": {
    "expression": {
      "patterns": [{ "include": "#letter" }, { "include": "#paren-expression" }]  // flags this line
    }, ...
```
> Object is missing property begin required by property patterns.

I like the idea of grouping language keys like this rather than putting them all in the main patterns. Is that wrong or something wrong with the schema?

**Comment by LeoDupont** [comment]
I'd like to add that the same flag occurs if one of the patterns specifies the `match` property but not `begin` or `end`, which appears to be an erroneous flag since one can use the former without the two latters, and vice versa (which is the case when scaffolding a language extension with `yo`).

**Comment by ExE-Boss** [comment]
This shouldn’t be happening.
