### ISSUE TITLE
begin and while missing end

### ISSUE THREAD

**Issue by matepek** [martinring/tmlanguage#7]
Hello,
The schema reports an error in case of `begin`+`while` pair.
It should be a valid combo.

https://github.com/martinring/tmlanguage/blob/master/tmlanguage.json#L132

Bests,

**Comment by sloane-shark** [comment]
https://github.com/matthewess/tmlanguage/blob/master/tmlanguage.json quickly hacked this together

**Comment by martinring** [comment]
Thank you @matthewess. I merged your changes.

**Comment by chharvey** [comment]
Can this be applied to `"contentName"` as well?

E.g.:
```json
{
	"contentName": "begin.abc.while.def",
	"begin": "abc",
	"while": "def"
}
```

[Working example](https://github.com/microsoft/vscode-markdown-tm-grammar/blob/b67ab3a350aad9e24b91b64b309e68d44df3dd92/build.js#L97)

Simple change:
```diff
"dependencies": {
-	"contentName": [ "begin", "end" ],
+	"contentName": { "anyOf": [[ "begin", "end" ], [ "begin", "while" ]] },
}
```

**Comment by martinring** [comment]
@chharvey thanks for the pointer... it's now fixed
